unbind r
bind r source-file ~/.tmux.conf
set-option -g default-shell /opt/homebrew/bin/zsh

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'omerxx/tmux-sessionx'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

set -g mouse on
set-window-option -g mode-keys vi

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g detach-on-destroy off

##### Display Popups ##### 
bind C-g display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "lazygit"
bind C-n command-prompt -p "Session name:" "run-shell 'tmux new-session -d -s %1 2>/dev/null || true'; switch-client -t %1"
bind C-y display-popup \
  -d "#{pane_current_path}" \
  -w 90% \
  -h 90% \
  -E "yazi"
bind C-t display-popup \
  -d "#{pane_current_path}" \
  -w 75% \
  -h 75% \
  -E "zsh"

##### Display Menu ##### 
bind d display-menu -T "#[align=centre]Dotfiles" -x C -y C \
  ".zshrc"            z  "display-popup -E 'nvim ~/.zshrc'" \
  ".tmux.conf"        t  "display-popup -E 'nvim ~/.tmux.conf'" \
  "Exit"              q  ""

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g @sessionx-bind 's'
#75 floax settings
set -g @floax-width '80%'
set -g @floax-height '80%'
set -g @floax-border-color 'blue'
set -g @floax-text-color 'white'
set -g @floax-bind 'p'
set -g @floax-change-path 'false'
# Dracula theme configuration
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g @dracula-plugins "time git"
set -g @dracula-time-format "%H:%M"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
