shell /usr/bin/zsh

background_opacity 0.9
dynamic_background_opacity yes

# Font configuration
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic

# Optional: adjust font size
font_size 11.0
